# Generated by Django 5.1.4 on 2024-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
