# Generated by Django 5.1.4 on 2024-12-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_enrollment_number'),
        ('teacher', '0003_alter_subject_class_name_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.ManyToManyField(related_name='students', to='teacher.class'),
        ),
    ]
