# Generated by Django 5.1.4 on 2024-12-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_class_name'),
        ('teacher', '0004_remove_subject_class_name_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ManyToManyField(blank=True, related_name='students', to='teacher.class'),
        ),
    ]
