# Generated by Django 5.1.4 on 2024-12-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_class_name'),
        ('teacher', '0007_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('submitted', 'Submitted')], default='pending', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='student.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='student_ass_student_9aa48d_idx'), models.Index(fields=['assignment'], name='student_ass_assignm_d88304_idx')],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
