# Generated by Django 5.1.4 on 2024-12-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], help_text='Grade for the submission (A, B, C, D, or F)', max_length=1, null=True),
        ),
    ]
