# Generated by Django 5.1.4 on 2024-12-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_subject_class_name_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'ordering': ['class_model']},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
    ]
