# Generated by Django 5.1.4 on 2024-12-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teachingassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('subject', 'class_model')},
        ),
    ]
