# Generated by Django 5.1.4 on 2024-12-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teachingassignment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass', to='teacher.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass', to='teacher.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass', to='teacher.teacher')),
            ],
            options={
                'unique_together': {('class_model', 'subject', 'title')},
            },
        ),
    ]
