# Generated by Django 5.1.4 on 2024-12-11 12:11

import school.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', school.manager.UserManager()),
            ],
        ),
    ]
